#nodeport service file
apiVersion: v1
kind: Service
metadata:
  namespace: nginx
  name: nginx-service
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 32767
    targetPort: 80
    nodePort: 30000
---
#loadbalancer
apiVersion: v1
kind: Service
metadata:
  namespace: nginx
  name: nginx-service
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80

---
#externalnames
apiVersion: v1
kind: Service
metadata:
  name: external-name
spec:
  selector:
    app: nginx
  ports:
  - port: 32001
    targetPort: 3306
  type: ExternalName
  externalName: <url>
  
---
#ingress
# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: default
spec:
  rules:
  - host: example.foo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
---
