#!/bin/bash

#Funtion to generate a random password
generate_password() {
    length=$1
    password=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w "$length" | head -n 1)
    echo "$password"
}

# Prompt user for username
read -p "Enter the username: " username

# Check if the user already exists
if id "$username" >/dev/null 2>&1; then
    echo "User $username already exists."
    read -p "Do you want to delete the existing user? (y/n): " delete_user

    if [[ $delete_user == "y" ]]; then
        # Delete the existing user and home directory
        userdel -r "$username"
        echo "Existing user $username and associated home directory deleted."
    else
        echo "Aborting user creation."
        exit 1
    fi
fi

# Generate a random password
password=$(generate_password 10)  # Change 10 to the desired password length

# Create the new user
useradd "$username"

# Set the generated password for the user
echo "$username:$password" | chpasswd

# Print the username and password
echo "Username: $username"
echo "Password: $password"
