apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-east-1
nodeGroups:
  - name: eks-demo-ng
    instanceType: t2.micro
    desiredCapacity: 5
    volumeSize: 80
    ssh:
      allow: true
    iam:
      withAddonPolicies: 
        autoScaler: true
        albIngress: true 
        cloudWatch: true 
cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
addons: 
- name: vpc-cni 
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
iam:
  withOIDC: true 
  serviceAccounts: 
  - metadata:
      name: aws-load-balancer-controller # create the needed service account for aws-load-balancer-controller while provisioning ALB/ELB by k8s ingress api
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: cluster-autoscaler # create the CA needed service account and its IAM policy
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true