apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secretpod
    image: nginx
    volumeMounts:
    - name: secretvolume
      mountPath: "/opt"
  volumes:
  - name: secretvolume
    secret:
      secretName: secret-01
