apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    app: nginx
    app: tomcat
spec:
  containers:
  - name: nginx-pod-1
    image: nginx
    ports:
      - containerPort: 8080
  - name: tomcat
    image: tomcat
    ports:
      - containerPort: 80
