apiVersion: v1
kind: configmap
metadata:
  name: configmap
  lables:
    key: value
data:
   game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
      - name: PLAYER_INITIAL_LIVES          
         valueFrom:
            configMapKeyRef:
              name: confimap
              key: player_initial_lives
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
  - name: config
    configMap:
      name: game-demo
      items:
      - key: "game.properties"
        path: "game.properties"
