#echo -n 'your-rds-username' | base64
#echo -n 'your-rds-password' | base64


apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: your-namespace
type: Opaque
data:
  username: "your-base64-encoded-username"
  password: "your-base64-encoded-password"
---
apiVersion: v1
kind: Pod
metadata:
  name: your-pod
spec:
  containers:
    - name: your-container
      image: your-image:tag
      env:
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: username
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: password
---
