apiVersion: v1
kind: Pod
metadata:
  name: etcd-with-grpc
spec:
  containers:
  - name: etcd
    image: registry.k8s.io/etcd:3.5.1-0
    command: [ "/usr/local/bin/etcd", "--data-dir",  "/var/lib/etcd", "--listen-client-urls", "http://0.0.0.0:2379", "--advertise-client-urls", "http://127.0.0.1:2379", "--log-level", "debug"]
    ports:
    - name: liveness-port
      containerPort: 8080
      hostPort: 8080

    livenessProbe: #check every 10 seconds (period seconds) to know the health of the container and if failed will restart
      httpGet:
        path: /healthz
        port: liveness-port
      failureThreshold: 3 # when probe fails continously 3 times a row, then k8s will take an action based on the pod specification.
      periodSeconds: 10 # check every 10 seconds

    startupProbe: #checks when container is ready to accept traffic
      httpGet:
        path: /healthz
        port: liveness-port
      failureThreshold: 30
      periodSeconds: 10
